# -*- coding: utf-8 -*-
"""atolye-veribilimi_veri_filtreleme_siralama1-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpO2GvMuh1YuEAmgAOsUKjY763axfwOR

# Techcareer Atölye: Veri Bilimine Giriş

   👩‍🎓 Merhaba,

   Bu mini proje Techcareer Atölye: Veri Bilimine Giriş eğitimi bitirme projem 💻 🧩


   Bu notebook, **country.csv** veri seti üzerinde **veri filtreleme ve sıralama** işlemlerini uygulamak için hazırlanmıştır.

## 1. Kütüphanelerin Yüklenmesi

 - Pandas
 - Numpy
"""

import pandas as pd
import numpy as np

"""## 2. Veri Seti

Çeşitli ülkelerle ilgili bir dizi **demografik**, **ekonomik** ve **coğrafi** veriyi içermektedir.  
    
Tabloda:  
- Her bir **satır** → bir ülkeyi temsil eder.  
- Her bir **sütun** → bu ülkelerle ilgili farklı özellikleri gösterir.  

İçerik:

- **Country**: Ülkenin adı  
- **Region**: Ülkenin bulunduğu bölge *(ör. Asya, Doğu Avrupa)*  
- **Population**: Ülkenin toplam nüfusu  
- **Area (sq. mi.)**: Ülkenin yüzölçümü *(mil kare olarak)*  
- **Pop. Density (per sq. mi.)**: Nüfus yoğunluğu *(mil kare başına kişi sayısı)*  
- **Coastline (coast/area ratio)**: Sahil uzunluğunun, ülkenin toplam alanına oranı  
- **Net migration**: Net göç oranı *(giren–çıkan nüfus farkı)*  
- **Infant mortality (per 1000 births)**: Bebek ölüm oranı *(1000 doğum başına)*  
- **GDP ($ per capita)**: Kişi başına düşen Gayri Safi Yurtiçi Hasıla (GSYİH)  
- **Literacy (%)**: Okur-yazarlık oranı  
- **Phones (per 1000)**: Her 1000 kişi başına düşen telefon sayısı  
- **Arable (%)**: Tarıma elverişli arazi yüzdesi  
- **Crops (%)**: Ekilebilir ürünlerin yüzdesi  
- **Other (%)**: Diğer arazi kullanımı yüzdesi  
- **Climate**: Ülkenin iklim kategorisi *(numerik bir değer)*  
- **Birthrate**: Doğum oranı  
- **Deathrate**: Ölüm oranı  
- **Agriculture**: Tarım sektörünün ekonomideki payı  
- **Industry**: Sanayi sektörünün ekonomideki payı  
- **Service**: Hizmet sektörünün ekonomideki payı
"""

# Doaya Yüklemee
from google.colab import files
uploaded = files.upload()

# Veri Seti
df = pd.read_csv('country.csv')
df

#  Veri Setini Tanıma
print("=== Veri Boyutu (Rows, Columns) ===")
print(df.shape)

print("\n=== Veri Tipleri ===")
print(df.dtypes)

print("\n=== Eksik Değer Sayıları ===")
print(df.isnull().sum())

print("\n=== Temel İstatistikler ===")
display(df.describe().T)

"""# 3. Görevler

## Görev 1: Nüfusa Göre Azalan Sırada Sıralama
"""

countries_by_population_desc = df.sort_values(by='Population', ascending=False)
countries_by_population_desc.head(10)

"""## Görev 2: GDP per capita Sütununa Göre Artan Sırada Sıralama

"""

countries_by_gdp_asc = df.sort_values(by='GDP ($ per capita)', ascending=True)
countries_by_gdp_asc.head(10)

"""## Görev 3: Population Sütunu 10 Milyonun Üzerinde Olan Ülkeler"""

pop_over_10m = df[df['Population'] > 10_000_000]
print('Nüfusu 10 milyonun üzerinde olan ülke sayısı:', pop_over_10m.shape[0])
pop_over_10m[['Country', 'Region', 'Population']].head(15)

"""## Görev 4: Literacy (%) Sütununa Göre Sıralama ve En Yüksek 5 Ülke


"""

top5_literacy = df.sort_values(by='Literacy (%)', ascending=False).head(5)
top5_literacy[['Country', 'Region', 'Literacy (%)']]

"""## Görev 5: Kişi Başı GSYİH 10.000'in Üzerinde Olan Ülkeler


"""

gdp_over_10000 = df[df['GDP ($ per capita)'] > 10_000]
print('Kişi başı GSYİH 10.000 üzerinde olan ülke sayısı:', gdp_over_10000.shape[0])
gdp_over_10000[['Country', 'Region', 'GDP ($ per capita)']].head(15)

"""## Görev 6: En Yüksek Nüfus Yoğunluğuna Sahip İlk 10 Ülke

"""

top10_density = df.sort_values(by='Pop. Density (per sq. mi.)', ascending=False).head(10)
top10_density[['Country', 'Region', 'Pop. Density (per sq. mi.)']]

print("Mutlu kodlamalar\n*gogo")