# -*- coding: utf-8 -*-
"""atolye-veribilimi_veri_gorsellestirme2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3kVsbsQHFgSJkuQKDzr5dA6Tr9uw4WL

# Techcareer Atölye: Veri Bilimine Giriş

   👩‍🎓 Merhaba,

   Bu mini proje Techcareer Atölye: Veri Bilimine Giriş eğitimi bitirme projem 💻 📊


   Bu notebook, **50_Startups.csv** veri seti üzerinde temel veri görselleştirme tekniklerini uygulamak için hazırlanmıştır.

## 1. Kütüphanelerin Yüklenmesi

 - Pandas
 - Numpy
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
sns.set(style='whitegrid')

"""# 2. Veri Seti

   **50 farklı startup şirketinin** çeşitli harcamalarını ve kârlılıklarını içermektedir.  

 **İçerik:**  

-  **R&D Spend (Ar-Ge Harcaması)**: Şirketin araştırma ve geliştirme (Ar-Ge) için harcadığı tutar.  

-  **Administration (Yönetim Harcaması)**: Şirketin yönetim giderleri için harcadığı tutar.  

-  **Marketing Spend (Pazarlama Harcaması)**: Şirketin pazarlama ve reklam faaliyetleri için harcadığı tutar.  

-  **State (Eyalet)**: Şirketin faaliyet gösterdiği eyalet (örneğin, New York, California, Florida).  

-  **Profit (Kâr)**: Şirketin elde ettiği toplam kâr.  


"""

# Doaya Yüklemee
from google.colab import files
uploaded = files.upload()

# Veri Seti
df = pd.read_csv('50_Startups.csv')
df

#  Veri Setini Tanıma
print("=== Veri Boyutu (Rows, Columns) ===")
print(df.shape)

print("\n=== Veri Tipleri ===")
print(df.dtypes)

print("\n=== Eksik Değer Sayıları ===")
print(df.isnull().sum())

print("\n=== Temel İstatistikler ===")
display(df.describe().T)

"""# 3. Görevler

## Görev 1: R&D Harcaması ve Kâr Arasındaki İlişki (Scatter Plot)
"""

plt.figure(figsize=(8,5))
plt.scatter(df["R&D Spend"], df["Profit"], c=df["R&D Spend"], cmap="viridis", alpha=0.7, edgecolor="k")
plt.colorbar(label="Profit ")
plt.xlabel("R&D Spend")
plt.ylabel("Profit")
plt.title("R&D Harcaması & Kâr Arasındaki İlişki")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

"""## Görev 2: Yönetim Harcamaları ve Kâr Arasındaki İlişki (Scatter Plot)

"""

plt.figure(figsize=(8, 5))
plt.scatter(df["Administration"], df["Profit"], c=df["Administration"], cmap="plasma", alpha=0.7, edgecolor="k")
plt.colorbar(label="Profit")
plt.xlabel("Administration")
plt.ylabel("Profit")
plt.title("Yönetim Harcaması & Kâr Arasındaki İlişki")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

"""## Görev 3: Eyaletlere Göre Ortalama Kâr (Bar Chart)

"""

state_profit = df.groupby("State", as_index=False)["Profit"].mean()
colors = sns.color_palette("coolwarm", len(state_profit))
plt.figure(figsize=(7,5))
plt.bar(state_profit["State"], state_profit["Profit"],color=colors, edgecolor="black")
plt.xlabel("Eyalet")
plt.ylabel("Ortalama Kâr")
plt.title("Eyaletlere Göre Ortalama Kâr")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.show()

"""## Görev 4: Harcama Türlerinin Karşılaştırması (Boxplot)

"""

plt.figure(figsize=(10, 5))
sns.boxplot(
    data=df[["R&D Spend", "Administration", "Marketing Spend"]],
    palette="coolwarm",
    orient="h"
plt.xlabel("Harcama Tutarı")
plt.title("Harcama Türlerinin Karşılaştırması (Yatay Boxplot)")
plt.grid(axis="x", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

print("Mutlu kodlamalar\n*gogo")