# -*- coding: utf-8 -*-
"""gogo_ile_veri_tipleri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFHqfk4nvpodc22d_f_L5f4R6My5iIbO
"""

# GOGO İLE VERİ TİPLERİ

# Veri Tipleri Uygulaması
"""
Bu çalışma, Python programlama dili aracılığıyla farklı veri tiplerinde (string, integer, float) değişken tanımlama
ve bu değişkenleri tek bir çıktı ifadesinde bütünleştirme uygulamasını içermektedir.
"""

# Veri tiplerine uygun değişken tanımlamaları

ad = "Hafize Gonca"                                    # string
soyad = "Cömert"                                       # string
yıl = 2023                                             # integer
akademik_ortalama = 3.94                               # float
calisma_alani = "Makine Öğrenmesi Algoritmaları Üzerine Bir Araştırma"                  # string
metodolojik_yaklasim = "çok kriterli karar verme ve derin öğrenme tabanlı modelleme"    # string
hedef = "disiplinler arası bilgi üretimi ve veri temelli karar süreçleri geliştirmek"   # string
takmaad = "gogo"                                      # string

# Tek print komutu ile akademik ifade
print(f"Ben {ad} {soyad}, {yıl} yılında sayısal yöntemler doktora programına başlamış bir araştırmacıyım.\n"
      f"Çalışmalarım aşağıdaki alanda yoğunlaşmaktadır:\n"
      f"{calisma_alani}\n"
      f"Akademik ortalamam {akademik_ortalama} olup, araştırma süreçlerimde {metodolojik_yaklasim} yöntemlerini kullanıyorum.\n"
      f"Uzun vadeli amacım {hedef}.\n"
      f"Kısaca ben {takmaad}.")