# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySWj9tAOsGv-cacShdZ5-w7qfejIfjdP
"""

#####################################################################################################
############################                     Numpy                   ############################
#####################################################################################################

### 1) 0 ile 9 arasındaki tam sayıları içeren tek boyutlu bir NumPy dizisi (array) oluşturun.

import numpy as np
arr = np.arange(10, dtype=int)
print(arr)

#####################################################################################################

### 2) Sadece sıfırlardan oluşan 3X4 boyutlarında bir matris oluşturun.

zeros_matrix = np.zeros((3, 4), dtype=int) # 3 satır, 4 sütun
print(zeros_matrix)

#####################################################################################################

### 3) Sadece birlerden oluşan 2X3 boyutlarında bir matris oluşturun.

ones_matrix = np.ones((2, 3), dtype=int) #2 satır, 3 sütun
print(ones_matrix)

#####################################################################################################

### 4) np.arange(12).reshape(3, 4) ile oluşturulan bir dizinin boyutunu (shape), eleman sayısını (size) ve kaç boyuta sahip olduğunu (ndim) bulun.

dizi = np.arange(12).reshape(3, 4)
print( "##################")
print("Dizi:\n", dizi)
print( "##################")
print("Shape:", dizi.shape) #boyut
print( "##################")
print("Size:", dizi.size)   #eleman sayısı
print( "##################")
print("ndim:", dizi.ndim)   #boyut sayısı

#####################################################################################################

### 5) [10, 20, 30, 40] listesini 64-bit tam sayı (int64) veri tipinde bir NumPy dizisine dönüştürün.

liste = [10, 20, 30, 40]
np_dizi = np.array(liste, dtype=np.int64)

print( "############################")
print(np_dizi)
print( "############################")
print("Veri tipi:", np_dizi.dtype)

#####################################################################################################

### 6) np.arange(20) dizisi içindeki 5'ten büyük ve 15'ten küçük olan tüm elemanları seçerek yeni bir dizi oluşturun.
dizi = np.arange(20)
yeni_dizi = dizi[(dizi > 5) & (dizi < 15)]

print( "###########################################################################")
print("yeni dizi:", dizi)
print( "###########################################################################")
print("5'ten büyük ve 15'ten küçük elemanlar:", yeni_dizi)

#####################################################################################################

### 7) • a = np.array([1, 2, 3]) ve b = np.array([4, 5, 6]) dizilerini oluşturun.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print( "############################")
print("a dizisi:", a)
print( "############################")
print("b dizisi:", b)

#####################################################################################################

### 8) • Bu iki dizinin toplamını ve çarpımını (eleman bazında) hesaplayın.

toplam = a + b
carpim = a * b

print( "############################")
print("Toplam:", toplam)
print( "############################")
print("Çarpım:", carpim)

#####################################################################################################

### 9) M = np.arange(1, 26).reshape(5, 5) matrisini oluşturun.

M = np.arange(1, 26).reshape(5, 5)

print( "###################")
print("M matrisi:\n", M)
print( "###################")

#####################################################################################################

### 10) Matrisin ikinci satırını ([6, 7, 8, 9, 10]) ve üçüncü sütununu ([3, 8, 13, 18, 23]) seçip ekrana yazdırın.

ikinci_satir = M[1, :]   # 2. satır (indeks 1)
ucuncu_sutun = M[:, 2]   # 3. sütun (indeks 2)

print( "##############################")
print("İkinci satır:", ikinci_satir)
print( "##############################")
print("Üçüncü sütun:", ucuncu_sutun)
print( "##############################")

#####################################################################################################

### 11) • Matris Çevirme (Transpose):

M_T = M.T  # Transpoz alma

print("####################")
print("Orijinal Matris (M):\n", M)
print("####################")
print("Transpozu (M.T):\n", M_T)
print("####################")

#####################################################################################################

### 12) 3X2 boyutunda rastgele tam sayılardan oluşan bir matris oluşturun ve bu matrisin transpozunu (devriğini) alın (2 X3 olmalı).

A = np.random.randint(0, 10, size=(3, 2))
A_T = A.T

print("##########################")
print("Orijinal Matris (3x2):\n", A)
print("###########################")
print("\nTranspozu (2x3):\n", A_T)
print("###########################")

#####################################################################################################

### 13) • Boş Eleman (NaN) Yönetimi:
### 14) dizi = np.array([1, 2, np.nan, 4, 5, np.nan, 7]) dizisindeki boş (NaN) eleman sayısını bulun.


dizi = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
nan_sayisi = np.isnan(dizi).sum()  # NaN değer sayısını bulur

print("###################################")
print("Dizi:", dizi)
print("###################################")
print("NaN (boş) eleman sayısı:", nan_sayisi)
print("###################################")

#####################################################################################################

### 15) 5X5 boyutlarında rastgele tam sayılardan oluşan bir matris oluşturun.

rastgele_matris = np.random.randint(0, 100, size=(5, 5))

print("######################")
print("5x5 Rastgele Matris:\n", rastgele_matris)
print("######################")

#####################################################################################################

### 16) Bu matrisin tüm elemanlarının ortalamasını, en büyük değerini ve sütun bazındaki standart sapmasını (axis=0 kullanarak) hesaplayın.

ortalama = rastgele_matris.mean()
en_buyuk = rastgele_matris.max()
std_sutun = rastgele_matris.std(axis=0)

print("######################################################################")
print("Matris:\n", rastgele_matris)
print("######################################################################")
print("Ortalama:", ortalama)
print("######################################################################")
print("En büyük değer:", en_buyuk)
print("######################################################################")
print("Standart sapma:\n", std_sutun)
print("######################################################################")

#####################################################################################################

### 17) a = np.array([1, 2]) ve b = np.array([3, 4]) dizilerini yatay (hstack) ve dikey (vstack) olarak birleştirin.

a = np.array([1, 2])
b = np.array([3, 4])

yatay = np.hstack((a, b))
dikey = np.vstack((a, b))

print("#############################################")
print("Yatay Birleştirme (hstack):", yatay)
print("#############################################")
print("Dikey Birleştirme (vstack):\n", dikey)
print("#############################################")

#####################################################################################################

### 18) A = np.array([[1, 2], [3, 4]]) ve B = np.array([[5, 6], [7, 8]]) matrislerini oluşturun.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print( "##################")
print("A matrisi:\n", A)
print( "##################")
print("B matrisi:\n", B)
print( "##################")

#####################################################################################################

### 19) Bu iki matrisin matris çarpımını (dot product) hesaplayın. (Skaler çarpım değil!)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matris_carpimi = np.dot(A, B)

print( "############################")
print("A matrisi:\n", A)
print( "############################")
print("B matrisi:\n", B)
print( "############################")
print("Matris Çarpımı (A · B):\n", matris_carpimi)
print( "############################")

#####################################################################################################

### 20) 5X5 boyutlarında rastgele bir matris oluşturun.

X = np.random.randn(5, 5)

print("##################################################################")
print("Rastgele 5x5 Matris:\n", X)
print("##################################################################")

#####################################################################################################

### 21) Bu matrisin her bir sütununa, o sütunun ortalama değerini çıkararak veriyi merkezleyin (ortalama sıfır olacak şekilde).

X = np.random.randn(5, 5)
sutun_ort = X.mean(axis=0)
X_merkezlenmis = X - sutun_ort

print("######################################################################")
print("Orijinal Matris:\n", X)
print("######################################################################")
print("Sütun Ortalamaları:\n", sutun_ort)
print("######################################################################")
print("Merkezlenmiş Matris (ortalama ≈ 0):\n", X_merkezlenmis)
print("######################################################################")

#####################################################################################################

### 22)	C = np.array([[4, 7], [2, 6]]) matrisini oluşturun.

C = np.array([[4, 7], [2, 6]])

print( "###############")
print("C matrisi:\n", C)
print( "###############")

#####################################################################################################

### 23) Matrisin determinantını hesaplayın.

C = np.array([[4, 7], [2, 6]])
det_C = np.linalg.det(C)

print( "###############################")
print("C matrisi:\n", C)
print( "###############################")
print("Determinant:", det_C)
print( "###############################")

#####################################################################################################

### 24) Matrisin tersini (inverse) hesaplayın ve ters matris ile orijinal matrisi çarparak birim matris (Identity Matrix) elde edip etmediğinizi kontrol edin.

C = np.array([[4, 7], [2, 6]])
C_inv = np.linalg.inv(C)
I = np.dot(C, C_inv)

print( "####################################")
print("C matrisi:\n", C)
print( "####################################")
print("C'nin tersi (inverse):\n", C_inv)
print( "####################################")
print("Birim Matris:\n", I)

#####################################################################################################

### 25) veri = np.array([1, 2, 1, 4, 5, 2, 7, 1]) dizisindeki benzersiz elemanları ve her bir elemanın kaç kez tekrarlandığını bulun.

veri = np.array([1, 2, 1, 4, 5, 2, 7, 1])
benzersiz, tekrar_sayisi = np.unique(veri, return_counts=True)

print( "#######################################")
print("Benzersiz elemanlar:", benzersiz)
print( "#######################################")
print("Her elemanın tekrar sayısı:", tekrar_sayisi)
print( "#######################################")

#####################################################################################################

### 26) dizi = np.random.randn(100) (Normal dağılımdan 100 rastgele sayı) dizisini oluşturun.

dizi = np.random.randn(100)

print("##########################################################################")
print("Normal Dağılımlı Rastgele Dizi:\n", dizi)
print("##########################################################################")

#####################################################################################################

### 27) Dizideki tüm değerleri -2 ve 2 aralığına kırpın (clip). Yani, -2'den küçük olanları -2 yapın, 2'den büyük olanları 2 yapın.

dizi = np.random.randn(100)
dizi_kirpildi = np.clip(dizi, -2, 2)

print("##########################################################################")
print("Orijinal Dizi:\n", dizi)
print("##########################################################################")
print("Kırpılmış Dizi (-2 ile 2 arası):\n", dizi_kirpildi)
print("##########################################################################")

#####################################################################################################

### 28) v1 = np.array([1, 2, 3]) ve v2 = np.array([4, 5, 6]) vektörlerini oluşturun.

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print( "###############")
print("v1:", v1)
print( "###############")
print("v2:", v2)
print( "###############")

#####################################################################################################

### 29) Bu iki vektörün nokta ürününü (inner product) ve dış ürününü (outer product) hesaplayın.


v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
nokta_urun = np.inner(v1, v2)
dis_urun = np.outer(v1, v2)

print( "###############################")
print("v1:", v1)
print( "###########################")
print("v2:", v2)
print( "###########################")
print("Nokta (inner) ürün:", nokta_urun)
print( "###########################")
print("Dış (outer) ürün:\n", dis_urun)
print( "###########################")

#####################################################################################################

### 30) 1.000.000 elemanlı büyük bir listeyi (py_list) ve aynı elemanları içeren bir NumPy dizisini (np_array) oluşturun.

py_list = list(range(1_000_000))
np_array = np.array(py_list)

print( "###############################")
print("Python listesi uzunluğu:", len(py_list))
print( "###############################")
print("NumPy dizisi boyutu:", np_array.shape)
print( "###############################")

#####################################################################################################

#####################################################################################################
print("Mutlu Kodlamalar")
print("Gogo")
#####################################################################################################